//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZumraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string TitleEN { get; set; }
        public string TitleAR { get; set; }
        public string ShortDescriptionEN { get; set; }
        public string ShortDescriptionAR { get; set; }
        public string DescriptionEN { get; set; }
        public string DescriptionAR { get; set; }
        public string Tags { get; set; }
        public string UPC { get; set; }
        public string SKU { get; set; }
        public decimal Price { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<int> AttachmentID { get; set; }
        public bool InStock { get; set; }
        public int NoInStock { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CDate { get; set; }
        public int CUser { get; set; }
    }
}
